### ISSUE TITLE
Merging AmdModuleCompiler

### ISSUE THREAD

**Issue by henrycatalinismith** [kimlai/melikeyradio#13]
I really like that [`AmdModuleCompiler`](https://github.com/kimlai/melikeyradio/blob/master/src/MeLikey/WebAppBundle/TwigJs/Compiler/AmdModuleCompiler.php) class. How would you feel about us including that code in our [Twig.js fork](https://github.com/basekit/twig.js)?

**Comment by kimlai** [comment]
Yes sure. I'm not completely happy with it though, making it extend a The `ModuleCompiler` as it is feels hackish. I was thinking about making the methods `compileClassHeader` and `compileClassFooter` abstract, and then having `AmdModuleCompiler` and `GoogModuleCompiler` extend `ModuleCompiler`.

I've only been toying around with both requirejs and twigjs so maybe you'd have some insight about this. I might try it myself if I find the time.

**Comment by kimlai** [comment]
Oh [cool](https://github.com/basekit/twig.js/commit/b8b5c1081fd79ebe7888c294736998afeea0e5f6). Any chance you'd try to merge it upstream ?

**Comment by henrycatalinismith** [comment]
Oops, sorry I forgot to answer this!

To be honest, I think @schmittjoh has a whole bunch of other projects that are keeping him pretty busy these days. I don't want to pile more pull requests onto him. I definitely think this would be a valuable addition to the main Twig.js project, but until that happens I'm happy to look after it in the BaseKit fork.

**Comment by schmittjoh** [comment]
Since you already contributed several patches to twig.js and seem to know the code base quite well, what do you think if I give you commit access so you can make your changes without going through pull requests?

**Comment by henrycatalinismith** [comment]
I think I could cope with that. We're pretty invested in twig.js at @basekit, which means I already have to tread quite carefully in the fork, or I risk breaking the product. It'd be really awesome to get our work merged back into the main repository where everyone else can benefit from it :)

**Comment by schmittjoh** [comment]
Great :)

I've added you as a collaborator to the repository.
